collections:
  - name: amazon.aws
  - name: cloud.terraform
  - name: hashicorp.terraform
    version: 1.2.0
  - name: hashicorp.vault
    version: 1.1.0
  - name: google.cloud
  - name: azure.azcollection
